defaults: &defaults
  database: antiqua_<%= ENV[ "RACK_ENV" ] %>
  host: 127.0.0.1
  identity_map_enabled: true
  port: 27017

demo:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
  host: data.antiqua.io

test:
  <<: *defaults
