defaults: &defaults
  host : 127.0.0.1
  port : 27017
  database: antiqua_<%= ENV[ "RACK_ENV" ] %>

demo:
  <<: *defaults

development:
  <<: *defaults

production:
  database: antiqua_<%= ENV[ "RACK_ENV" ] %>
  uri: <%= ENV['MONGOHQ_URL'] %>

test:
  <<: *defaults

