#!/usr/bin/env bash
original_args=$@
builtin type -p foreman &> /dev/null
if [ $? -eq 0 ] ; then
  foreman_command='foreman'
else
  foreman_command='bundle exec foreman'
fi
eval "exec $foreman_command $original_args"
